// <auto-generated />
using MagicVilla_VillaAPI.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContex))]
    [Migration("20240125091527_SeedVillaTable")]
    partial class SeedVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.models.Villamodel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("occupancy")
                        .HasColumnType("int");

                    b.Property<int>("sqft")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("villamodels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            Details = "good",
                            ImageUrl = "",
                            Name = "heart villa",
                            Rate = 690.0,
                            occupancy = 5,
                            sqft = 520
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            Details = "good",
                            ImageUrl = "",
                            Name = "modern villa",
                            Rate = 300.0,
                            occupancy = 6,
                            sqft = 740
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            Details = "good",
                            ImageUrl = "",
                            Name = "lovely villa",
                            Rate = 100.0,
                            occupancy = 5,
                            sqft = 340
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            Details = "good",
                            ImageUrl = "",
                            Name = "sweet villa",
                            Rate = 300.0,
                            occupancy = 5,
                            sqft = 640
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
